spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: "user-server"
          uri: "http://localhost:8082"
          predicates:
            - Path=/user/**

        - id: "URL-SERVER"
          uri: "http://localhost:8083"
          predicates:
            - Path=/url/**
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
