spring:
  application:
    name: url-server
  data:
    mongodb:
      port: 27017
      host: localhost
      database: shortlink
    redis:
       port: 6379
       host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8083
